apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-logs.conf
    @INCLUDE filter-stdout.conf
    @INCLUDE output-stdout.conf

  input-logs.conf: |
    [INPUT]
        Name              tail
        Path              /tmp/*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-stdout.conf: |
    [FILTER]
        Name                stdout
        Match               *

  output-stdout.conf: |
    [OUTPUT]
        Name            stdout
        Match           *
